services:
  qdrant:
    image: qdrant/qdrant:v1.5.1
    volumes:
      - ./qdrant_data:/qdrant/storate
    ports:
      - 6333:6333
      - 6334:6334
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
